### ISSUE TITLE
Enhance for Traefik's ForwardAuth feature?

### ISSUE THREAD

**Issue by d4z3x** [itzg/saml-auth-proxy#10]
This is pretty cool. I've been struggling with getting a proper SAML library for Go, but haven't been successful with the in house one we use... Anyhow, this is interesting implementation of crewjam's SAML lib for some of us newbies at SAML.

Anyhow, I thought this would be really used if modified a bit as a Forward Auth server for Traefik.

**Comment by itzg** [comment]
This application was also my way to learn SAML and was glad to find crewjam’s library eased the curve. 

I haven’t yet used traefik, but it sounds like you might be onto an interesting enhancement. Feel free to submit a PR, even if it is just a draft and we can collaborate to see if it’s a good fit.

**Comment by d4z3x** [comment]
I have a basic crewjam and traefik implementation kind of working. I can share that if you like to take a look? May be easier to discuss over email.

**Comment by itzg** [comment]
Sounds good. You can grab my email address from https://github.com/itzg . You're also welcome to grab bits and pieces from this auth proxy code if the traefik forward auth support is too much of a force-fit.

**Comment by itzg** [comment]
Resolved by #38
