### ISSUE TITLE
Support Allow IDP Initiated

### ISSUE THREAD

**Issue by kennethklee** [itzg/saml-auth-proxy#11]
Can we support the `AllowIDPInitiated` flag?

Trying to create a portal to an app behind this proxy and getting a `Forbidden` on the `/saml/acs` page after login. The error in the logs say:

```
ERROR: `InResponseTo` does not match any of the possible request IDs (expected [])
```

From some research it appears we need to enable the `AllowIDPInitiated` flag.

Thoughts?

**Comment by itzg** [comment]
That looks like it should be easy to support with the SAML library being used.

**Comment by itzg** [comment]
I don't know of a way to test this myself, so I wondering if you could test out https://github.com/itzg/saml-auth-proxy/releases/tag/1.4.0-rc1 . The new command-line argument is `---allow-idp-initiated`

**Comment by kennethklee** [comment]
Tested it out and works beautifully. Thank you!

**Comment by itzg** [comment]
Thanks for testing that. It is now released in https://github.com/itzg/saml-auth-proxy/releases/tag/1.4.0
