### ISSUE TITLE
Configurable cookie domain

### ISSUE THREAD

**Issue by kennethklee** [itzg/saml-auth-proxy#15]
We'd like to have the proxy at `login.company.com` and have apps behind the proxy at `app.company.com`.

Can we make the cookie domain configurable? So it can be set to the parent domain, say, `.company.com`.

**Comment by itzg** [comment]
It looks like that should be an easy change. I had to remind myself what I had done currently and it uses the configured base URL's host as the cookie domain. I can add a config option to override that behavior.

**Comment by itzg** [comment]
https://github.com/itzg/saml-auth-proxy/releases/tag/1.6.0 now includes the new `--cookie-domain` option.

**Comment by kennethklee** [comment]
Tested with 1.6.1. Works perfectly! Thanks @itzg

**Comment by itzg** [comment]
Excellent. I'm glad you noticed/tested the 1.6.1 release since during testing of the cookie domain I noticed the token cookie was getting relayed to the backend. Seemed like a good thing to lock down.
