### ISSUE TITLE
Traefik forward_auth protocol

### ISSUE THREAD

**Issue by kennethklee** [itzg/saml-auth-proxy#35]
Can we add an endpoint to verify authentication using [Traefik forward_auth](https://doc.traefik.io/traefik/middlewares/http/forwardauth/#forwardauth). This would also work with [Caddy's forward_auth directive](https://caddyserver.com/docs/caddyfile/directives/forward_auth).

i.e. add the following endpoint: `/_verify`. on authenticated, returns 204 with saml headers in the response headers, and without body content. otherwise, the normal redirect to the saml idp login.

**Comment by itzg** [comment]
I like the idea of that. I'm just wondering if that will require some special intercepting of the SAML library. Feel free to create PR for this one.

**Comment by itzg** [comment]
Thanks for the additional info and pinging this. Sorry I haven't gotten around to this one yet and glad to hear you have a workaround for now. 

BTW I'm not sure what caddy code is but this is implemented in Go.

**Comment by itzg** [comment]
Github "closed" the issue but once 1.9.0 release is built I'd appreciate any testing you can do. Feel free to reopen if you find any issues.

Sorry for this taking so very long to implement.

**Comment by itzg** [comment]
Released in https://github.com/itzg/saml-auth-proxy/releases/tag/1.9.0

**Comment by kennethklee** [comment]
oh sweet! thanks itzg!

also realized this is a dup of #10. so closes that
