### ISSUE TITLE
Get "http://locahost:3000/": dial tcp: lookup locahost on 127.0.0.53:53: server misbehaving

### ISSUE THREAD

**Issue by rsuhendro** [itzg/saml-auth-proxy#43]
I'm "Trying it out" however from SAMLTest's login page instead of access to Grafana, I got the above message. Appreciate for any hints or pointer...

Hendro

**Comment by itzg** [comment]
An error related to port 53 means you have DNS issues in your system.

**Comment by rsuhendro** [comment]
Oops...the problem is with http://locahost:3000... it should be  http://localhost:3000. I just copy paste from the instruction : --backend-url http://locahost:3000 \. 
Thanks...
