### ISSUE TITLE
after login, the /_verify check redirects to the wrong URI

### ISSUE THREAD

**Issue by kennethklee** [itzg/saml-auth-proxy#54]
I have an app running at `my-app.my-domain.com`, and saml-auth-proxy running at `sso.my-domain.com`, and forward_auth setup to `https://sso.my-domain.com/_verify`.

Problem:
1. user visits `my-app.my-domain.com`
2. is redirected to login and logs in
3. gets redirected to `sso.my-domain.com/_verify` instead of the original `my-app.my-domain.com`.

To help, the forward_auth protocol includes two headers to the /_verify request -- `X-Forwarded-Method` and `X-Forwarded-Uri`.

Potential solution?
The cookie tracker could detect the `/_verify` path and use `x-forwarded-uri` header instead of `r.URL.String` in line https://github.com/itzg/saml-auth-proxy/blob/565baf90e335635f41ac28ac968884d11d57c105/server/request_tracker_cookie.go#L37

If it helps, I have an old old fork that does this (probably not the best check): https://github.com/kennethklee/saml-auth-proxy/blob/4cba73af48ba5aebcb5f22d16a6231a542bcb112/server/request_tracker_cookie.go#L27-L34

**Comment by itzg** [comment]
That seems reasonable and you're welcome to PR your changes. What kind of proxy verification were you considering there, if any?

**Comment by kennethklee** [comment]
In terms of proxy verification, I realized the cookie already checks the domain, and Caddy has a build in `trusted_proxies` config users can set if needed.  

Anyway, here's my PR ^
