### ISSUE TITLE
Just plain THANK YOU!

### ISSUE THREAD

**Issue by bfqrst** [itzg/saml-auth-proxy#6]
Geoff, this little project of yours helped us a ton. Frankly it was exactly the piece of glue that was missing between a backend that doesn't natively support SAML and our in house SAML IDP. 

Appreciate your work!
**Thanks** from Hannover, Germany!
Ralph

**Comment by itzg** [comment]
I’m so glad to hear that! Likewise this has served my workplace well for some grafana and kibana deployments using ADFS.
