### ISSUE TITLE
Redirects are not propagated

### ISSUE THREAD

**Issue by odormond** [itzg/saml-auth-proxy#9]
Hello!

Thanks for your nice work!

I've unfortunately identified an issue with it regarding the handling of HTTP 3xx (redirect) responses.

When the proxied server returns an HTTP redirect response the net/http Client will follow it before returning the final response (it will follow up to 10 redirects). As redirect responses are not returned to the client this will make him think that the content which is eventually returned belongs to the original URL requested while it actually belongs to a different one. As a consequence, relative links within the page are broken.

According to https://golang.org/pkg/net/http/#Client, this can be fixed by setting `CheckRedirect` on the `Client` to a function returning `ErrUseLastResponse`.

This can easily be tested by proxying an nginx server with autoindex and requesting the listing of a directory with an URL like `http://proxy/path/to/directory` (without a trailing slash) as nginx will redirect to an URL with a trailing slash `http://proxy/path/to/directory/`. With the redirect swallowed by the proxy, the client will get the directory listing and when clicking on any of them it will be directed to `http://proxy/path/to/entry` instead of the correct `http://proxy/path/to/directory/entry`.

Cheers,

Olivier

**Comment by marco-m-pix4d** [comment]
@odormond could we provide @itzg with a nginx configuration to reproduce the problem?

**Comment by itzg** [comment]
Thanks @odormond I’ll take a look at this and try to fix it today. I also have a debug web server where I could add a redirect mechanism, so don’t worry too much about the nginx config.

**Comment by itzg** [comment]
This fix is now released https://github.com/itzg/saml-auth-proxy/releases/tag/1.2.1

**Comment by itzg** [comment]
BTW, if you're interested, I updated my web-debug-server to accept a `--redirects` declaration:

https://github.com/itzg/web-debug-server/releases/tag/1.1.0

**Comment by marco-m-pix4d** [comment]
Thanks @itzg !

**Comment by odormond** [comment]
Thanks a lot @itzg ! :-)
